### ISSUE TITLE
Adding and removing rows, and using emptyTableTemplate for data table

### ISSUE THREAD

**Issue by st-clair-clarke** [krishna-agarwal/momentum-table#27]
Hi Krishna,
Seasons greeting and congrats on a first class implementation of material2 datatable.

Among the features you describe for your implementation is 'Empty Row templating'
Going through the example at stackblitz I cannot find an example.

I would also like to know how do I use 'emptyTableTemplate: TemplateRef<any>' to create an empty table and instantiation, after which I could add rows

In addition please let me know how to remove a row.

Thanks for your help.

Cheers

**Comment by krishna-agarwal** [comment]
Hi @st-clair-clarke 
Thank you for kind words, Glad to know that you find it useful. Will try to document this soon so that it will be more useful.

Regarding Empty row Template:
This could be used to show msgs(like 'loading' or 'no record found' etc) when datatable is empty. It is used in stackblitz example to show 'loading' msg while fetching data.
`<ng-template mTemplate="emptyTable">
    {{emptyMsg}}
  </ng-template>`

Empty Table creation : 
To create table we need to bind table to an array of values to render rows, to create an empty table we can bind to an empty array, and later we can push or remove item from that array to add or remove row from table. 
`<m-table [value]=array>
</m-table>`   

I hope this would help.

Thanks.

**Comment by st-clair-clarke** [comment]
Hi Krishna!
Great to hear from you so quickly! I was hoping for a quick reply but doubtful at the same time. Thanks a lot for your help. I am trying to migrate from primeng data-table to material2 and your implementation is just great. I hope you will maintain it in the future and add more features as material2 improve.

One feature I like in primeng was using a dialog to edit a row item. What do you think about that?

Cheers and thanks again.

**Comment by krishna-agarwal** [comment]
Hi @st-clair-clarke,
Thanks again for your kind words.
This datatable is inspired by primeng only, and will try to implement more primeng features in near future.  Will start with row edit dialog once I get time. Meanwhile I guess you could use **onRowClick** event and open a dialog.
`<m-table (onRowClick)="rowClick($event)"></m-table>` 

Thanks.
